### ISSUE TITLE
2.4.3.2 M2 Report Component Diagram

### ISSUE THREAD

**Issue by donhitme34** [INF2001/TEAM-PROJECT-P11-3#101]
Task title ID: 2.4.3.2 M2 Report Component Diagram
What is the task about? This task is aimed at writing up the Report Component Diagram part for the M2 report.
What are the goals of the task? To produce a detailed and thorough writeup of the Component Diagram and its specifics in the report.
Success or completion criteria: When the writeup is done up professionally and the fine details regarding the component diagram are all included in the writeup.
Allocated time: 5 days
Start date and end date of the issue/task. Start: 22/10/2023 End: 26/10/2023
Who is the owner? Gabriel
The status of the task: In Progress
What is the Priority of the task? High

**Comment by zrieel** [comment]
Describe the work done in detail: Writeup for the M2 Report Component Diagram has been completed. Work has also been peer-reviewed by team members to ensure that it is clear to understand.
Has this work been committed to the repo? Yes
How does the work affect the completion deadline? It would not change the project completion dateline.
Are there any changes to the success or completion criteria of the task? No, there was no changes to the completion criteria of the task.
Start date and end date of the work done for this comment. Start: 22/10/2023 End: 25/10/2023
