### ISSUE TITLE
3.1 Architecture Design

### ISSUE THREAD

**Issue by farhanhan1** [INF2001/TEAM-PROJECT-P11-3#136]

**Comment by khaiprograms** [comment]
Task title ID: https://github.com/INF2001/TEAM-PROJECT-P11-3/issues/136
What is the task about? This task is focused on detailing a proposed architecture to the solution the team has come up with. Additionally, it details the design for which the architecture will be based on.
What are the goals of the task? To provide a clear and detailed design to allow clear demarcation of programming responsibilities.
Success or completion criteria: When the whole team is agreeable to the proposed architecture design.
Allocated time: 4 days
Start date and end date of the issue/task Start: 15/11/2023 End: 18/11/2023
Who is the owner? Khairul
The status of the task: Completed
What is the Priority of the task? High

**Comment by khaiprograms** [comment]
1. The architecture design is designed and well received.
2. The work has been added into the M3 report and is pushed to the repository.
3. It does not affect the completion deadline and the project is able to be completed in time.
4. There are no changes to the success or completion criteria of the task.
5. Start date 15/11/2023, end date 18/11/2023.
