### ISSUE TITLE
1.11 Functional Requirements

### ISSUE THREAD

**Issue by donhitme34** [INF2001/TEAM-PROJECT-P11-3#23]

**Comment by jasonyjk** [comment]
1. Task title ID: **#18** 
2. What is the task about? **The task involves documenting a set of clear and concise functional requirements for Music School Workload Management System (Website).** 
3. What are the goals of the task? **Define and capture the intended behavior of the system by specifying the required services, tasks, and functions it should perform to meet the needs of stakeholders, including teachers, managers, and IT administrators who will be utilizing the system.**
4. Success or completion criteria. **All functional requirements are documented clearly and concisely, without any unresolved ambiguities, it also adheres to the established requirements from the project descriptions and information gathered from the client, Mr David Cheng.**
5. Allocated time: **48 hours**
6. Start date and end date of the issue/task **08/09/2023 to 08/09/2023**
7. Who is the owner? **Jason**
8. The status of the tasks. **Completed**
9. What is the Priority of the task? **HIGH**

**Comment by jasonyjk** [comment]
1. In our detailed work process, two members were tasked to conduct a comprehensive documentation of the functional requirement. These information were gathered via two sources, by identifying and interpreting all the possible requirements from the project description writeup that capture the intended behavior of the system. This behavior may be expressed as services, tasks or functions the system is required to perform. In addition, we also check against the requirement gathered during our client meeting with Mr. David Cheng.
2. The work has been updated onto the M1 Report.
3. The project timeline remains unaffected, and it continues to progress as per the established schedule.
4. No, there are no changes to the success or completion criteria of the task. The criteria remain as originally defined.
5. Start date 12/09/2023 end date 13/09/2023
