### ISSUE TITLE
2.1.1 User Authentication, Account Management and Database Components

### ISSUE THREAD

**Issue by donhitme34** [INF2001/TEAM-PROJECT-P11-3#83]
1. Task title ID: https://github.com/INF2001/TEAM-PROJECT-P11-3/issues/83

2. What is the task about: Design a component diagram focusing on "User Authentication, Account Management and Database Component" for the website to be developed for the client.

3. Goals of the task: Define the core functionalities for each of the sub components. The task would also to illustrate the interactions and data flows between these components and finally prioritise clarity and logical structuring to ensure ease of understanding and efficient future coding.

4. Success or completion criteria: Components are distinctly represented, with clear demarcation of their roles and functionalities. Interactions between components are logical, without ambiguities, and clearly depict data flows.

5. Allocated time: 72 hours

6. Start date and end date of the task: 12/10/2023 start, 14/10/2023 end

7. Owner: Khairul

8. Status of the task: To-Do

9. Priority of the task: High

**Comment by khaiprograms** [comment]
i. Describe the work done in detail: The required subcomponents (and its relevant interactions) have been implemented in the overall component diagram

ii. Has this work been committed to the repo? Yes

iii. How does the work affect the completion deadline? It would not change the project completion deadline

iv. Are there any changes to the success or completion criteria of the task? No, there was no changes to the completion criteria of the task

v. Start date and end date of the work done for this comment. Start: 12/10/2023 End: 14/10/2023
